<?php

namespace Vpos;

return [
    '3DPayHosting' => [
        'action' => '',
        'parameters' => [
            ['name' => 'clientid', 'optional' => false],
            ['name' => 'oid', 'optional' => false],
            ['name' => 'amount', 'optional' => false],
            ['name' => 'okUrl', 'optional' => false],
            ['name' => 'failUrl', 'optional' => false],
            ['name' => 'storetype', 'optional' => false],
            ['name' => 'firmaadi', 'optional' => false],
            ['name' => 'islemtipi', 'optional' => false],
            ['name' => 'taksit', 'optional' => false],
            ['name' => 'currency', 'optional' => false],
            ['name' => 'rnd', 'optional' => false],
            ['name' => 'hash', 'optional' => false],
            ['name' => 'description', 'optional' => true],
            ['name' => 'xid', 'optional' => true],
            ['name' => 'lang', 'optional' => true],
            ['name' => 'email', 'optional' => true],
            ['name' => 'userid', 'optional' => true],
            ['name' => 'refreshtime', 'optional' => true],
            ['name' => 'Faturafirma', 'optional' => true],
            ['name' => 'Fismi', 'optional' => true],
            ['name' => 'Fadres', 'optional' => true],
            ['name' => 'Fadres2', 'optional' => true],
            ['name' => 'Fil', 'optional' => true],
            ['name' => 'Filce', 'optional' => true],
            ['name' => 'Fpostakodu', 'optional' => true],
            ['name' => 'tel', 'optional' => true],
            ['name' => 'Fulkekod', 'optional' => true],
            ['name' => 'NakliyeFirma', 'optional' => true],
            ['name' => 'tismi', 'optional' => true],
            ['name' => 'tadres', 'optional' => true],
            ['name' => 'tadres2', 'optional' => true],
            ['name' => 'til', 'optional' => true],
            ['name' => 'tilce', 'optional' => true],
            ['name' => 'tpostakodu', 'optional' => true],
            ['name' => 'tulkekod', 'optional' => true],
            ['name' => 'itemnumber1', 'optional' => true],
            ['name' => 'productcode1', 'optional' => true],
            ['name' => 'qty1', 'optional' => true],
            ['name' => 'desc1', 'optional' => true],
            ['name' => 'id1', 'optional' => true],
            ['name' => 'price1', 'optional' => true],
            ['name' => 'total1', 'optional' => true],
        ]
    ],
    'PayHosting' => [
        'action' => '',
        'parameters' => [
            ['name' => 'pan', 'optional' => false],
            ['name' => 'Ecom_Payment_Card_ExpDate_Year', 'optional' => false],
            ['name' => 'Ecom_Payment_Card_ExpDate_Month', 'optional' => false],
            ['name' => 'clientid', 'optional' => false],
            ['name' => 'oid', 'optional' => false],
            ['name' => 'amount', 'optional' => false],
            ['name' => 'okUrl', 'optional' => false],
            ['name' => 'failUrl', 'optional' => false],
            ['name' => 'storetype', 'optional' => false],
            ['name' => 'islemtipi', 'optional' => false],
            ['name' => 'currency', 'optional' => false],
            ['name' => 'taksit', 'optional' => false],
            ['name' => 'lang', 'optional' => false],
            ['name' => 'rnd', 'optional' => false],
            ['name' => 'hash', 'optional' => false],
            ['name' => 'description', 'optional' => true],
            ['name' => 'xid', 'optional' => true],
            ['name' => 'email', 'optional' => true],
            ['name' => 'userid', 'optional' => true],
            ['name' => 'refreshtime', 'optional' => true],
            ['name' => 'Faturafirma', 'optional' => true],
            ['name' => 'Fismi', 'optional' => true],
            ['name' => 'Fadres', 'optional' => true],
            ['name' => 'Fadres2', 'optional' => true],
            ['name' => 'Fil', 'optional' => true],
            ['name' => 'Filce', 'optional' => true],
            ['name' => 'Fpostakodu', 'optional' => true],
            ['name' => 'tel', 'optional' => true],
            ['name' => 'Fulkekod', 'optional' => true],
            ['name' => 'NakliyeFirma', 'optional' => true],
            ['name' => 'tismi', 'optional' => true],
            ['name' => 'tadres', 'optional' => true],
            ['name' => 'tadres2', 'optional' => true],
            ['name' => 'til', 'optional' => true],
            ['name' => 'tilce', 'optional' => true],
            ['name' => 'tpostakodu', 'optional' => true],
            ['name' => 'tulkekod', 'optional' => true],
            ['name' => 'itemnumber1', 'optional' => true],
            ['name' => 'productcode1', 'optional' => true],
            ['name' => 'qty1', 'optional' => true],
            ['name' => 'desc1', 'optional' => true],
            ['name' => 'id1', 'optional' => true],
            ['name' => 'price1', 'optional' => true],
            ['name' => 'total1', 'optional' => true],
        ]
    ],
];